# XY相遇派交易模块配置

# 数据源配置
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 使用 xypai_trade 数据库（交易相关表：orders, payments等）
          url: ${datasource.xypai-trade-master.url}
          username: ${datasource.xypai-trade-master.username}
          password: ${datasource.xypai-trade-master.password}

# Dubbo配置
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${spring.cloud.nacos.server-addr}
    group: ${spring.cloud.nacos.discovery.group}
    parameters:
      namespace: ${spring.cloud.nacos.discovery.namespace}

